language: node_js
node_js:
    - "node"
sudo: false
cache:
  directories:
    - $(npm config get cache)
install:
    - npm config set prefer-offline true
    - npm install
script:
    - echo -e "\x1b\x5b35;1m*** Parsing docs...\x1b\x5b0m"
    - npm run parse
    - echo -e "\x1b\x5b35;1m*** Parsing complete\x1b\x5b0m"
    - echo -e "\x1b\x5b35;1m*** Generating docs...\x1b\x5b0m"
    - npm run build
    - echo -e "\x1b\x5b35;1m*** Doc generation complete\x1b\x5b0m"
